// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/v1/greeter.proto

package publicv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_public_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_public_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_public_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_public_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_public_v1_greeter_proto protoreflect.FileDescriptor

const file_public_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x17public/v1/greeter.proto\x12\tpublic.v1\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2U\n" +
	"\fGreetService\x12E\n" +
	"\bSayHello\x12\x1a.public.v1.SayHelloRequest\x1a\x1b.public.v1.SayHelloResponse\"\x00B\xb0\x01\n" +
	"\rcom.public.v1B\fGreeterProtoP\x01ZJgithub.com/k07g/sv1/internal/pkg/infrastructure/grpc/pb/public/v1;publicv1\xa2\x02\x03PXX\xaa\x02\tPublic.V1\xca\x02\n" +
	"Public_\\V1\xe2\x02\x16Public_\\V1\\GPBMetadata\xea\x02\n" +
	"Public::V1b\x06proto3"

var (
	file_public_v1_greeter_proto_rawDescOnce sync.Once
	file_public_v1_greeter_proto_rawDescData []byte
)

func file_public_v1_greeter_proto_rawDescGZIP() []byte {
	file_public_v1_greeter_proto_rawDescOnce.Do(func() {
		file_public_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_v1_greeter_proto_rawDesc), len(file_public_v1_greeter_proto_rawDesc)))
	})
	return file_public_v1_greeter_proto_rawDescData
}

var file_public_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_public_v1_greeter_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: public.v1.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: public.v1.SayHelloResponse
}
var file_public_v1_greeter_proto_depIdxs = []int32{
	0, // 0: public.v1.GreetService.SayHello:input_type -> public.v1.SayHelloRequest
	1, // 1: public.v1.GreetService.SayHello:output_type -> public.v1.SayHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_v1_greeter_proto_init() }
func file_public_v1_greeter_proto_init() {
	if File_public_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_v1_greeter_proto_rawDesc), len(file_public_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_v1_greeter_proto_goTypes,
		DependencyIndexes: file_public_v1_greeter_proto_depIdxs,
		MessageInfos:      file_public_v1_greeter_proto_msgTypes,
	}.Build()
	File_public_v1_greeter_proto = out.File
	file_public_v1_greeter_proto_goTypes = nil
	file_public_v1_greeter_proto_depIdxs = nil
}
